[theme]
primaryColor = "#7f5af0"
backgroundColor = "#16161a"
secondaryBackgroundColor = "#242629"
textColor = "#fffffe"
font = "monospace"

[server]
enableStaticServing = true
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
maxMessageSize = 200

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
